language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk11
addons:
  postgresql: "9.6"
install: true
script:
  - mvn install
before_script:
  - "createuser -d tribe"
  - "psql -c 'create database tribe;' -U tribe postgres"
after_failure:
  - find . -name '*.dump*' -exec echo '=====' \; -exec echo {} \; -exec cat {} \;
