version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: tribe
          POSTGRES_DB: tribe

    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx128m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ .Revision }}
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies-

      - run: mvn install

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ .Branch }}-{{ .Revision }}

      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
